export const example_values = {
    'age': ['Select age', '18-24 years old', '25-34 years old', '35-44 years old', '45-54 years old', '55 years old and above'],
    'gender': ['Select gender', 'Male', 'Female', 'Prefer not to say'],
    'place_of_residence': ['Place of residence', 'Yangon', 'Nay Pyi Taw', 'Mandalay'],
    'occupation': ['Occupation', 'Student', 'Employed(full-time)', 'Employed(Part-Time)', 'Civil Servant'],
    'comfort_of_collecting_info': ['Select an option', 'Yes', 'No', 'Uncertain'],
    'security_issues_present': ['Select an option', 'Yes', 'No'],
    'missing_features': ['Select an option', 'Yes', 'No'],
    'contact_customer_support_for_any_issues': ['Select an option', 'Yes', 'No'],
    'recommend_the_mobile_payment_applications_you_use_to_others': ['Select an option', 'Yes', 'No']
};

export const defaultFormData = {
    age: '',
    gender: '',
    place_of_residence: '',
    occupation: '',
    in_store_payments: '',
    paying_bills: '',
    transferring_money: '',
    ease_of_navigation: '',
    visually_appealing: '',
    ease_of_finding_features: '',
    security_features: '',
    comfort_of_collecting_info: '',
    security_issues_present: '',
    bill_payments: '',
    money_transfers: '',
    top_up_capabilities: '',
    promotions_discounts: '',
    loyalty_programs: '',
    missing_features: '',
    reliability: '',
    speed_of_transactions: '',
    customer_support: '',
    contact_customer_support_for_any_issues: '',
    recommend_the_mobile_payment_applications_you_use_to_others: ''
};

export const questionTexts = {
    age: "How old are you?",
    gender: "What is your gender?",
    place_of_residence: "Where do you live?",
    occupation: "What is your occupation?",
    in_store_payments: "Do you want in-store payments in the payment app? ",
    paying_bills: "Do you want the app to be able to pay bills?",
    transferring_money: "What level of convenience do you need in transferring money?",
    ease_of_navigation: "How easy should the navigation be?",
    visually_appealing: "Does the app need to be visual appealing?",
    ease_of_finding_features: "How easy do you want to find features in the app?",
    security_features: "How secured the app should be?",
    comfort_of_collecting_info: "Are you comfortable with the app collecting your info?",
    security_issues_present: "Will you be able to deal with security issues?",
    bill_payments: "What the level of experience with bill payments should be?",
    money_transfers: "What the level of experience with money transfers should be?",
    top_up_capabilities: "What the level of experience with topup capabilities should be?",
    promotions_discounts: "How much do you want promotions and discounts?",
    loyalty_programs: "How should the loyalty programs be?",
    missing_features: "Are you okay with the app having missing features?",
    reliability: "How reliable it should be?",
    speed_of_transactions: "How fast speed of transactions should be?",
    customer_support: "How good the customer support should be?",
    contact_customer_support_for_any_issues: "Do you want to be able to contact customer support for issues?",
    recommend_the_mobile_payment_applications_you_use_to_others: "Would you want to be able to recommend the mobile payment applications you use to others?"
};